version: '3.8'
services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  db_data:
  mongo_data:
